
import apiClient from './index'; 

export const generateQuiz = async (quizInput) => {
    /**
     * Generates a quiz based on a topic, number of questions, and difficulty.
     * @param {object} quizInput - Object containing topic, num_questions, difficulty.
     * @returns {Promise<object>} - The generated quiz data.
     */
    try {
        const response = await apiClient.post('/quizzes/generate', quizInput);
        return response.data;
    } catch (error) {
        // console.error('API Error: generateQuiz', error.response?.data || error.message);
        throw error.response?.data || error.message;
    }
};

export const generateQuizFromFile = async (file, numQuestions, difficulty) => {
    /**
     * Generates a quiz from an uploaded PDF file.
     * @param {File} file - The PDF file to upload.
     * @param {number} numQuestions - The desired number of questions.
     * @param {string} difficulty - The difficulty level.
     * @returns {Promise<object>} - The generated quiz data.
     */
    try {
        const formData = new FormData();
        formData.append('file', file);
        formData.append('num_questions', numQuestions);
        formData.append('difficulty', difficulty);
        const response = await apiClient.post('/quizzes/generate-from-file', formData, {
            headers: {
                'Content-Type': 'multipart/form-data', 
            },
        });
        return response.data;
    } catch (error) {
        // console.error('API Error: generateQuizFromFile', error.response?.data || error.message);
        throw error.response?.data || error.message;
    }
};

export const submitQuiz = async (quizId, submissionData) => {
    /**
     * Submits user answers for a quiz.
     * @param {string} quizId - The ID of the quiz.
     * @param {object} submissionData - Object containing user's answers.
     * @returns {Promise<object>} - The quiz result data.
     */
    try {
        const response = await apiClient.post(`/quizzes/${quizId}/submit`, submissionData);
        return response.data;
    } catch (error) {
        // console.error('API Error: submitQuiz', error.response?.data || error.message);
        throw error.response?.data || error.message;
    }
};

export const getUserQuizzes = async () => {
    /**
     * Retrieves all quizzes generated by the current user.
     * @returns {Promise<Array<object>>} - A list of quiz data.
     */
    try {
        const response = await apiClient.get('/quizzes/'); 
        return response.data;
    } catch (error) {
        // console.error('API Error: getUserQuizzes', error.response?.data || error.message);
        throw error.response?.data || error.message;
    }
};

export const getQuizById = async (quizId) => {
    /**
     * Retrieves a specific quiz by its ID.
     * @param {string} quizId - The ID of the quiz.
     * @returns {Promise<object>} - The quiz data.
     */
    try {
        const response = await apiClient.get(`/quizzes/${quizId}`);
        return response.data;
    } catch (error) {
        // console.error('API Error: getQuizById', error.response?.data || error.message);
        throw error.response?.data || error.message;
    }
};